# docker compose file to start linux specific services in development environment
services:
  # the workspace container which is used in VSCode on Linux
  workspace:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        WORKSPACE: "/home/ros/workspace"
        USER: "ros"
    cap_add:
      - SYS_PTRACE
    environment:
      DISPLAY: :0
      WAYLAND_DISPLAY: :0
      # Needed for rendering of opengl
      LIBGL_ALWAYS_SOFTWARE: 1
      LIBGL_ALWAYS_INDIRECT: 0
      # for unix audio / video
      PULSE_SERVER: unix:/run/user/1000/pulse/native
      XDG_RUNTIME_DIR: /run/user/1000
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    user: ros
    volumes:
      - ..:/home/ros/workspace
      # for unix audio / video
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000:/run/user/1000
      - /etc/alsa:/etc/alsa
      - /usr/share/alsa:/usr/share/alsa
      - ~/.config/pulse:/.config/pulse
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
